# Generated by Django 4.1.4 on 2024-01-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tank_Name', models.CharField(max_length=255)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Cap_MCM', models.FloatField()),
                ('Block', models.CharField(max_length=255)),
                ('Taluk', models.CharField(max_length=255)),
                ('District', models.CharField(max_length=255)),
            ],
        ),
    ]
