# Generated by Django 4.1.4 on 2024-05-27 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterbodies_app', '0006_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
    ]
