# Generated by Django 4.1.4 on 2024-06-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterbodies_app', '0007_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('taluk', models.CharField(max_length=100)),
                ('block', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('waterbody_type', models.CharField(max_length=100)),
                ('waterbody_id', models.CharField(max_length=100, unique=True)),
                ('survey_number', models.CharField(max_length=100)),
                ('ownership', models.CharField(max_length=100)),
                ('availability', models.CharField(max_length=100)),
            ],
        ),
    ]
