# Generated by Django 4.1.4 on 2024-06-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterbodies_app', '0008_pond'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pond',
            name='waterbody_id',
            field=models.CharField(max_length=100),
        ),
    ]
