# Generated by Django 4.1.4 on 2024-06-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterbodies_app', '0009_alter_pond_waterbody_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pond',
            name='id',
        ),
        migrations.AlterField(
            model_name='pond',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
