# Generated by Django 4.1.4 on 2024-06-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterbodies_app', '0010_remove_pond_id_alter_pond_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_name', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('taluk', models.CharField(max_length=100)),
                ('block', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('jurisdiction_name', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('waterbody_type', models.CharField(max_length=100)),
                ('waterbody_id', models.CharField(max_length=100)),
                ('survey_number', models.CharField(max_length=100)),
                ('ownership', models.CharField(max_length=100)),
                ('waterbody_availability', models.CharField(max_length=100)),
            ],
        ),
    ]
