# Generated by Django 4.1 on 2024-08-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterbodies_app', '0013_oorani'),
    ]

    operations = [
        migrations.CreateModel(
            name='KMLFilesz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('kml_file', models.FileField(upload_to='kml_files/')),
                ('original_kmz_file', models.FileField(blank=True, null=True, upload_to='kmz_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
