# Generated by Django 4.1 on 2024-08-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterbodies_app', '0014_kmlfilesz'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoOwaterbody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=255)),
                ('ponds_oo', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('taluk', models.CharField(blank=True, max_length=255, null=True)),
                ('block', models.CharField(blank=True, max_length=255, null=True)),
                ('panchayat', models.CharField(blank=True, max_length=255, null=True)),
                ('village', models.CharField(blank=True, max_length=255, null=True)),
                ('pond_type', models.CharField(blank=True, max_length=255, null=True)),
                ('cap_mcm', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('fpl_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mwl_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pbl_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sto_dep_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('catchment', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('wat_spr_ar', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('bund_len_m', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('dis_cusecs', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
            ],
        ),
    ]
