# Generated by Django 4.1 on 2024-08-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterbodies_app', '0015_poowaterbody'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterbodiesTank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('block', models.CharField(blank=True, max_length=255, null=True)),
                ('panchayat', models.CharField(blank=True, max_length=255, null=True)),
                ('village', models.CharField(blank=True, max_length=255, null=True)),
                ('tank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tank_type', models.CharField(blank=True, max_length=255, null=True)),
                ('ayacut_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('wat_spr_ar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cap_mcm', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('no_of_sluices', models.IntegerField(blank=True, null=True)),
                ('sluices_type', models.CharField(blank=True, max_length=255, null=True)),
                ('bund_len_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tbl_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mwl_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ftl_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('unique_id', models.CharField(max_length=255)),
                ('sto_depth_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('catchment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('no_of_weirs', models.IntegerField(blank=True, null=True)),
                ('weir_length_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('low_sill_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dis_cusecs', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
            ],
        ),
    ]
