# Generated by Django 4.1 on 2024-09-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterbodies_app', '0021_fencetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_code', models.CharField(max_length=10)),
                ('district', models.CharField(max_length=100)),
                ('block_code', models.CharField(max_length=10)),
                ('block', models.CharField(max_length=100)),
                ('village_code', models.CharField(max_length=10)),
                ('village', models.CharField(max_length=100)),
                ('habitation_code', models.CharField(max_length=10)),
                ('habitation', models.CharField(max_length=100)),
            ],
        ),
    ]
