# Generated by Django 4.1 on 2024-09-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterbodies_app', '0022_habitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrbanLocalBodies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_code', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('ward_code', models.CharField(max_length=50)),
                ('ward', models.CharField(max_length=100)),
            ],
        ),
    ]
