# Generated by Django 4.1 on 2024-09-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterbodies_app', '0023_urbanlocalbodies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurisdiction',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
