# Generated by Django 4.1 on 2024-10-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterbodies_app', '0030_bundfunctionalities_conditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatchmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
