# Generated by Django 4.2.16 on 2024-10-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterbodies_app', '0033_waterbodyfieldreviewerreviewdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cropings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
